# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score_blue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Pontos Azul'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score_red',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Pontos Vermelho'),
        ),
    ]
