# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170211_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score_red',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10, verbose_name='Pontos Vermelho'),
        ),
    ]
