# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170211_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score_blue',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10, verbose_name='Pontos Azul'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(default='Em Breve', editable=False, max_length=100, verbose_name='Status'),
        ),
    ]
