# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('score_red', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10, verbose_name='Pontos Vermelho')),
                ('score_blue', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10, verbose_name='Pontos Azul')),
                ('status', models.CharField(default='Em Breve', editable=False, max_length=100, verbose_name='Status')),
                ('start', models.DateTimeField(null=True, verbose_name='Come\xe7a em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('game_time', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Tempo do Jogo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Esporte',
                'verbose_name_plural': 'Esportes',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Sport'),
        ),
    ]
